{
    'name': 'MCP Webhook Hub',
    'summary': 'Secure MCP endpoint and signed webhook automation hub for Odoo',
    'description': 'Connect AI agents and automation systems to Odoo with scoped API keys, audit logs, signed webhooks and retry logs.',
    'version': '19.0.1.0.4',
    'category': 'Extra Tools',
    'author': 'White Sausage Labs',
    'website': 'https://whitesausagelabs.com',
    'support': 'support@whitesausagelabs.com',
    'license': 'OPL-1',
    'price': 210.00,
    'currency': 'EUR',
    'depends': ['base', 'mail', 'sale', 'account', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/api_key_views.xml',
        'views/audit_log_views.xml',
        'views/webhook_rule_views.xml',
        'views/webhook_log_views.xml',
        'views/menu_views.xml',
    ],
    'images': [
        'static/description/preview.png',
        'static/description/main_screenshot.png',
        'static/description/screenshot_webhook_rules.png',
        'static/description/screenshot_audit_logs.png',
        'static/description/screenshot_webhook_logs.png',
        'static/description/screenshot_api_key_form.png',
        'static/description/screenshot_webhook_rule_form.png',
    ],
    'installable': True,
    'application': True,
}
